"""
ModelCreationAgent — Generate a Python payment model from governing documents
and deal setup data using deterministic template-based code generation.

No LLM / OpenAI dependency — all work is performed by reading structured
extractions and assembling Python code sections from templates.
"""

from __future__ import annotations

import json
import logging
import textwrap
from pathlib import Path
from typing import Any

from backend.agents.base_agent import AgentBase
from backend.agents.agent_tools import ToolRegistry
from backend.common.confidence import ConfidenceScore, ConfidenceTier
from backend.abs.config.constants import (
    CONFIDENCE_HIGH_THRESHOLD,
    CONFIDENCE_LOW_THRESHOLD,
    OUTPUT_TOLERANCE,
)
from backend.abs.deal_scope import DealScope
from backend.abs.generation.data_prep import load_deal_setup, load_classes_setup
from backend.abs.skills.graph_builder import load_graph, get_waterfall_order
from config import KTSConfig

logger = logging.getLogger(__name__)


# ── Template fragments used to assemble the generated model ──────────────

_MODEL_HEADER = '''\
"""
Auto-generated payment model for {deal_id}.
Generated by ModelCreationAgent — deterministic, template-based.
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any
'''

_CONSTANTS_SECTION = '''
# ── Constants (extracted from governing documents) ───────────────────────
{constants_code}
'''

_CLASSES_SECTION = '''
# ── Class Definitions ────────────────────────────────────────────────────
CLASS_NAMES = {class_names}
'''

_WATERFALL_SECTION = '''
# ── Waterfall Rules (in payment order) ───────────────────────────────────
WATERFALL_ORDER = {waterfall_order}
'''

_RUN_FUNCTION = '''
# ── Run Entry Point ──────────────────────────────────────────────────────

def run(data_path: Path | str, month: int) -> str:
    """Execute the payment model for a single month.

    Returns CSV-formatted output string.
    """
    data_path = Path(data_path)
    # Load monthly data
    deal_setup = _load_kv_csv(data_path / "deal_setup.csv")
    class_balances = _load_class_balances(data_path, month)

    results: list[dict[str, Any]] = []
    available_funds = float(deal_setup.get("available_funds", "0"))

    for step in WATERFALL_ORDER:
        step_name = step.get("name", step.get("id", ""))
        target_class = step.get("target_class", "")
        payment_type = step.get("payment_type", "interest")

        if target_class and target_class in class_balances:
            balance = class_balances[target_class]
            payment = _calculate_payment(
                payment_type, balance, deal_setup, available_funds,
            )
            available_funds = max(available_funds - payment, 0.0)
            results.append({{
                "class_name": target_class,
                "step": step_name,
                "payment_type": payment_type,
                "payment": round(payment, 2),
                "ending_balance": round(balance - payment if payment_type == "principal" else balance, 2),
            }})

    return _results_to_csv(results)


# ── Helpers ──────────────────────────────────────────────────────────────

def _load_kv_csv(path: Path) -> dict[str, str]:
    """Read a two-column (field, value) CSV into a dict."""
    result: dict[str, str] = {{}}
    if not path.exists():
        return result
    with open(path, newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            key = row.get("field", "").strip()
            val = row.get("value", "").strip()
            if key:
                result[key] = val
    return result


def _load_class_balances(data_path: Path, month: int) -> dict[str, float]:
    """Load class balances — from classes_setup (month 1) or prior run."""
    if month == 1:
        cs_path = data_path / "classes_setup.csv"
    else:
        cs_path = data_path / f"runs/month_{{month - 1}}/output.csv"
    balances: dict[str, float] = {{}}
    if cs_path.exists():
        with open(cs_path, newline="", encoding="utf-8") as fh:
            for row in csv.DictReader(fh):
                name = row.get("class_name", "")
                bal = float(row.get("original_balance", row.get("ending_balance", "0")))
                if name:
                    balances[name] = bal
    return balances


def _calculate_payment(
    payment_type: str,
    balance: float,
    deal_setup: dict[str, str],
    available_funds: float,
) -> float:
    """Deterministic payment calculation based on rule type."""
    if payment_type == "interest":
        rate = float(deal_setup.get("interest_rate", "0.05")) / 12
        return min(balance * rate, available_funds)
    elif payment_type == "principal":
        return min(balance, available_funds)
    return 0.0


def _results_to_csv(results: list[dict]) -> str:
    """Convert results list to CSV string."""
    if not results:
        return ""
    cols = list(results[0].keys())
    lines = [",".join(cols)]
    for row in results:
        lines.append(",".join(str(row.get(c, "")) for c in cols))
    return "\\n".join(lines)
'''


class ModelCreationAgent(AgentBase):
    """
    Generate a Python payment model from governing documents and deal
    setup data.  The generation is fully deterministic — the agent reads
    structured extractions produced by earlier pipeline stages and
    assembles code from predefined template fragments.
    """

    agent_name = "model_creation"

    # Template file lives in the repo root.
    TEACHING_TEMPLATE_PATH = Path("Teaching_Model_Template/sample_teaching_model.py")

    def __init__(
        self,
        config: KTSConfig,
        deal_scope: DealScope,
        tool_registry: ToolRegistry,
        llm_callable=None,
    ) -> None:
        super().__init__(config, deal_scope=deal_scope, tool_registry=tool_registry, llm_callable=llm_callable)

    # ------------------------------------------------------------------
    # Prompt structure
    # ------------------------------------------------------------------

    def _get_mission(self) -> str:
        return (
            "Generate a Python payment model from governing documents and "
            "deal setup data using deterministic template-based code generation. "
            "No LLM calls — read extractions, apply templates, emit runnable code."
        )

    def _get_actions(self) -> list[str]:
        return [
            "Load governing docs from deal_path/governing_docs/.",
            "Load deal_setup.csv and classes_setup.csv.",
            "Load the deal dependency graph and compute waterfall order.",
            "Read the teaching model template as structural reference.",
            "Extract constants, class info, and waterfall rules from extractions.",
            "Assemble Python source from template fragments.",
            "Save generated model to deal_path/model/payment_model.py.",
        ]

    def _get_output_spec(self) -> str:
        return (
            "dict with keys:\n"
            "  model_path: str — path to the generated payment_model.py\n"
            "  sections_generated: list[str] — code sections created\n"
            "  constants_extracted: dict[str, Any] — constants written\n"
        )

    def _get_validation_rules(self) -> list[str]:
        return [
            "Generated model must be syntactically valid Python.",
            "Every constant must trace to an extraction or governing doc.",
            "Waterfall order must reflect the deal graph.",
            "Model must expose a run(data_path, month) callable.",
        ]

    # ------------------------------------------------------------------
    # Core execution
    # ------------------------------------------------------------------

    def _run(self, task: dict[str, Any]) -> dict[str, Any]:
        deal_path = self.deal_scope.deal_path

        # 1. Load deal setup data
        try:
            deal_setup = load_deal_setup(deal_path)
        except FileNotFoundError:
            return {"status": "error", "error": "deal_setup.csv not found", "sections_generated": []}

        try:
            classes_df = load_classes_setup(deal_path)
        except FileNotFoundError:
            return {"status": "error", "error": "classes_setup.csv not found", "sections_generated": []}

        # 2. Load extractions / governing docs
        extractions = self._load_extractions(deal_path)
        constants = self._extract_constants(extractions, deal_setup)

        # 3. Load graph and waterfall order
        waterfall_order = self._load_waterfall_order(deal_path, extractions)

        # 4. Build class list
        class_names = {
            str(row["class_name"]): idx
            for idx, (_, row) in enumerate(classes_df.iterrows(), start=1)
        }

        # 5. Assemble model source
        sections_generated: list[str] = []
        code_parts: list[str] = []

        code_parts.append(_MODEL_HEADER.format(deal_id=self.deal_scope.deal_id))
        sections_generated.append("header")

        constants_code = self._render_constants(constants)
        code_parts.append(_CONSTANTS_SECTION.format(constants_code=constants_code))
        sections_generated.append("constants")

        code_parts.append(_CLASSES_SECTION.format(class_names=repr(class_names)))
        sections_generated.append("classes")

        code_parts.append(
            _WATERFALL_SECTION.format(waterfall_order=json.dumps(waterfall_order, indent=4))
        )
        sections_generated.append("waterfall")

        code_parts.append(_RUN_FUNCTION)
        sections_generated.append("run_function")

        model_source = "\n".join(code_parts)

        # 6. Write to disk
        model_dir = deal_path / "model"
        model_dir.mkdir(parents=True, exist_ok=True)
        model_path = model_dir / "payment_model.py"
        model_path.write_text(model_source, encoding="utf-8")
        logger.info("Generated payment model at %s", model_path)

        # 7. Optional critique loop (LLM-only, fully deterministic fallback)
        critique_rounds_run = 0
        if (
            self._llm is not None
            and getattr(self.config, "abs_critique_enabled", False)
        ):
            max_rounds = int(getattr(self.config, "abs_critique_max_rounds", 3))
            target = float(getattr(self.config, "abs_critique_target", 0.92))
            model_source, critique_rounds_run = self._run_critique_loop(
                model_source=model_source,
                constants=constants,
                waterfall_order=waterfall_order,
                max_rounds=max_rounds,
                target=target,
            )
            if critique_rounds_run > 0:
                model_path.write_text(model_source, encoding="utf-8")
                logger.info("Critique loop ran %d round(s); model rewritten", critique_rounds_run)

        return {
            "model_path": str(model_path),
            "sections_generated": sections_generated,
            "constants_extracted": constants,
            "critique_rounds": critique_rounds_run,
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _load_extractions(self, deal_path: Path) -> dict[str, list[dict]]:
        """Load all extraction JSON files from deal_path/extractions/."""
        extractions: dict[str, list[dict]] = {}
        ext_dir = deal_path / "extractions"
        if not ext_dir.exists():
            logger.warning("No extractions directory at %s", ext_dir)
            return extractions
        for json_file in sorted(ext_dir.glob("*.json")):
            try:
                data = json.loads(json_file.read_text(encoding="utf-8"))
                section = json_file.stem
                items = data if isinstance(data, list) else data.get("items", [data])
                extractions[section] = items
            except (json.JSONDecodeError, OSError) as exc:
                logger.warning("Skipping extraction %s: %s", json_file, exc)
        return extractions

    def _extract_constants(
        self,
        extractions: dict[str, list[dict]],
        deal_setup: dict[str, Any],
    ) -> dict[str, Any]:
        """Pull constants from extractions and deal setup."""
        constants: dict[str, Any] = {}

        # From deal_setup CSV
        for key in ("interest_rate", "original_balance", "closing_date",
                     "first_payment_date", "servicer_fee_rate"):
            if key in deal_setup:
                constants[key] = deal_setup[key]

        # From definitions extraction
        for defn in extractions.get("definitions", []):
            term = defn.get("term", defn.get("name", ""))
            value = defn.get("value", defn.get("numeric_value"))
            if term and value is not None:
                safe_key = term.lower().replace(" ", "_").replace("-", "_")
                constants[safe_key] = value

        return constants

    def _load_waterfall_order(
        self,
        deal_path: Path,
        extractions: dict[str, list[dict]],
    ) -> list[dict[str, Any]]:
        """Load waterfall order from graph or fall back to extractions."""
        try:
            graph = load_graph(deal_path / "graph" / "deal_graph.json")
            order = get_waterfall_order(graph)
            if order:
                return [{"name": step, "id": step} for step in order]
        except Exception as exc:
            logger.info("Graph waterfall order unavailable: %s", exc)

        # Fallback: use waterfall_rules from extractions
        rules = extractions.get("waterfall_rules", extractions.get("waterfall", []))
        return [
            {
                "name": r.get("id", r.get("step", f"step_{i}")),
                "id": r.get("id", f"step_{i}"),
                "target_class": r.get("target_class", r.get("class", "")),
                "payment_type": r.get("payment_type", "interest"),
            }
            for i, r in enumerate(rules, start=1)
        ]

    @staticmethod
    def _render_constants(constants: dict[str, Any]) -> str:
        """Render constants dict as Python assignment lines."""
        lines: list[str] = []
        for key, value in sorted(constants.items()):
            lines.append(f"{key.upper()} = {repr(value)}")
        return "\n".join(lines) if lines else "# No constants extracted"

    def _run_critique_loop(
        self,
        model_source: str,
        constants: dict[str, Any],
        waterfall_order: list[dict],
        max_rounds: int,
        target: float,
    ) -> tuple[str, int]:
        """Refine the generated model via an LLM critique loop.

        Submits the generated code to the LLM for review.  If the LLM returns
        actionable suggestions AND the self-reported quality score is below
        *target*, applies inline suggestions and re-evaluates for up to
        *max_rounds* iterations.

        Returns (final_model_source, rounds_run).  On any LLM error the original
        source is returned unchanged.
        """
        import re as _re

        current_source = model_source
        rounds_run = 0

        for round_num in range(1, max_rounds + 1):
            constants_summary = ", ".join(
                f"{k}={repr(v)}" for k, v in list(constants.items())[:8]
            )
            waterfall_summary = " → ".join(
                step.get("name", step.get("id", "?")) for step in waterfall_order[:6]
            )

            critique_prompt = (
                "You are reviewing a Python ABS payment model.\n"
                "Evaluate it for:\n"
                "  1. Correctness — does run(data_path, month) match the waterfall order?\n"
                "  2. Traceability — are all constants derived from the deal data?\n"
                "  3. Completeness — are all waterfall steps present?\n\n"
                f"Known constants: {constants_summary}\n"
                f"Expected waterfall order: {waterfall_summary}\n\n"
                "Model source:\n"
                "```python\n"
                f"{current_source}\n"
                "```\n\n"
                "Reply in this exact JSON format:\n"
                '{"quality": <0.0–1.0>, "issues": ["..."], "improved_source": "<full corrected Python source or empty string>"}\n'
                "If no improvements are needed, set improved_source to empty string."
            )

            try:
                raw = self._llm(critique_prompt, None)
                # Extract the JSON block
                m = _re.search(r"\{.*\}", raw, _re.DOTALL)
                if not m:
                    logger.debug("Critique round %d: no JSON found in LLM response", round_num)
                    break

                import json as _json
                critique = _json.loads(m.group(0))
                quality = float(critique.get("quality", 0.0))
                improved = (critique.get("improved_source") or "").strip()

                logger.info(
                    "Critique round %d: quality=%.2f, has_improvements=%s",
                    round_num,
                    quality,
                    bool(improved),
                )

                rounds_run = round_num

                if quality >= target:
                    # Model meets target — stop early
                    break

                if improved:
                    # Validate that the improved source is syntactically valid Python
                    try:
                        import ast as _ast
                        _ast.parse(improved)
                        current_source = improved
                    except SyntaxError as syn_err:
                        logger.warning(
                            "Critique round %d produced invalid Python (%s); discarding",
                            round_num,
                            syn_err,
                        )
                        # Keep current_source unchanged; try one more round
                else:
                    # No improvement proposed — stop
                    break

            except Exception as exc:
                logger.warning("Critique loop round %d failed: %s", round_num, exc)
                break

        return current_source, rounds_run

    # ------------------------------------------------------------------
    # Quality scoring overrides
    # ------------------------------------------------------------------

    def _score_completeness(self, result: Any, task: dict) -> float:
        """Check that key sections were generated."""
        sections = result.get("sections_generated", [])
        required = {"header", "constants", "classes", "waterfall", "run_function"}
        present = required & set(sections)
        return 10.0 * len(present) / len(required) if required else 8.0

    def _score_accuracy(self, result: Any, task: dict) -> float:
        """Check that constants were extracted."""
        constants = result.get("constants_extracted", {})
        return 10.0 if len(constants) >= 3 else max(6.0, 10.0 * len(constants) / 3)

    def _score_confidence(self, result: Any, task: dict) -> ConfidenceScore:
        sections = result.get("sections_generated", [])
        constants = result.get("constants_extracted", {})
        value = min(1.0, (len(sections) / 5) * 0.5 + (min(len(constants), 5) / 5) * 0.5)
        tier = self._categorize_confidence(value)
        return ConfidenceScore(
            value=value,
            tier=tier,
            reasoning=f"{len(sections)} sections, {len(constants)} constants",
        )

    def _get_artifacts(self, result: Any) -> list[str]:
        model_path = result.get("model_path", "")
        return [model_path] if model_path else []
