"""
QAAgent — Answer questions about deal documents using vector search.

Retrieves semantically relevant chunks from the deal's vector store,
formats answers with citations (section, page references), and
validates that the queried deal has been ingested.

No LLM / OpenAI dependency — answers are assembled from retrieved
chunks, not generated by a language model.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from backend.agents.base_agent import AgentBase
from backend.agents.agent_tools import ToolRegistry
from backend.common.confidence import ConfidenceScore, ConfidenceTier
from backend.abs.config.constants import CONFIDENCE_HIGH_THRESHOLD, CANONICAL_SECTIONS
from backend.abs.deal_scope import DealScope
from config import KTSConfig

logger = logging.getLogger(__name__)


class QAAgent(AgentBase):
    """
    Answer questions about deal documents using vector search.

    Workflow:
    1. Validate that the deal has been ingested (vectors exist).
    2. For each question in the task, run vector_search() for
       semantically similar chunks.
    3. Optionally refine with search_by_section() for section-specific
       queries.
    4. Format answers with citations (section name, page reference).
    5. Return structured answers with confidence scores.
    """

    agent_name = "qa_research"

    DEFAULT_N_RESULTS = 5

    def __init__(
        self,
        config: KTSConfig,
        deal_scope: DealScope,
        tool_registry: ToolRegistry,
        llm_callable=None,
    ) -> None:
        super().__init__(config, deal_scope=deal_scope, tool_registry=tool_registry, llm_callable=llm_callable)

    # ------------------------------------------------------------------
    # Prompt structure
    # ------------------------------------------------------------------

    def _get_mission(self) -> str:
        return (
            "Answer questions about deal documents by retrieving relevant "
            "chunks via vector search and formatting answers with citations."
        )

    def _get_actions(self) -> list[str]:
        return [
            "Validate that the deal has been ingested (vector collection exists).",
            "For each question: run vector_search() for relevant chunks.",
            "Use search_by_section() for section-specific queries.",
            "Format answers with citations (section, page references).",
            "Score confidence based on retrieval similarity.",
        ]

    def _get_output_spec(self) -> str:
        return (
            "dict with keys:\n"
            "  answers: list[dict] — each with:\n"
            "    question: str\n"
            "    answer: str\n"
            "    citations: list[dict] — {section, page, score}\n"
            "    confidence: float\n"
        )

    def _get_validation_rules(self) -> list[str]:
        return [
            "Only answer questions for ingested deals.",
            "Every answer must include at least one citation.",
            "Confidence must reflect retrieval quality.",
            "Unanswerable questions must be flagged explicitly.",
        ]

    # ------------------------------------------------------------------
    # Core execution
    # ------------------------------------------------------------------

    def _run(self, task: dict[str, Any]) -> dict[str, Any]:
        deal_path = self.deal_scope.deal_path

        # 1. Validate ingestion
        if not self._is_deal_ingested(deal_path):
            questions = self._extract_questions(task)
            return {
                "answers": [
                    {
                        "question": q,
                        "answer": "Deal has not been ingested. Please run the ingestion pipeline first.",
                        "citations": [],
                        "confidence": 0.0,
                    }
                    for q in questions
                ],
            }

        # 2. Process questions
        questions = self._extract_questions(task)
        n_results = task.get("n_results", self.DEFAULT_N_RESULTS)
        answers: list[dict[str, Any]] = []

        for question in questions:
            if self._is_dependency_question(question):
                answer = self._answer_dependency_question(deal_path, question)
            else:
                answer = self._answer_question(deal_path, question, n_results)
            answers.append(answer)

        return {"answers": answers}

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _extract_questions(task: dict[str, Any]) -> list[str]:
        """Extract question(s) from the task dict."""
        if "question" in task:
            return [task["question"]]
        if "questions" in task:
            return list(task["questions"])
        # Treat any string value as a question
        for v in task.values():
            if isinstance(v, str) and v.strip().endswith("?"):
                return [v]
        return ["What are the key terms of this deal?"]

    @staticmethod
    def _is_dependency_question(question: str) -> bool:
        q = question.lower()
        keywords = [
            "depend on",
            "depends on",
            "dependency",
            "dependencies",
            "resolution tree",
            "what is required to compute",
        ]
        return any(k in q for k in keywords)

    @staticmethod
    def _answer_dependency_question(deal_path: Path, question: str) -> dict[str, Any]:
        tree_path = deal_path / "graph" / "definition_resolution_trees.json"
        if not tree_path.exists():
            return {
                "question": question,
                "answer": "Definition resolution artifacts are not available for this deal.",
                "citations": [],
                "confidence": 0.0,
            }

        try:
            trees = json.loads(tree_path.read_text(encoding="utf-8"))
        except Exception:
            return {
                "question": question,
                "answer": "Definition resolution artifacts are unreadable.",
                "citations": [],
                "confidence": 0.0,
            }

        if not isinstance(trees, list) or not trees:
            return {
                "question": question,
                "answer": "No definition resolution trees were found.",
                "citations": [],
                "confidence": 0.0,
            }

        q_lower = question.lower()
        target = next(
            (t for t in trees if str(t.get("term_name", "")).lower() in q_lower),
            trees[0],
        )

        deps = QAAgent._flatten_dependencies(target)
        citations = [
            {
                "section": d.get("source_reference", "definitions"),
                "page": "",
                "score": 0.9,
            }
            for d in deps[:5]
        ]

        if deps:
            dep_names = ", ".join(sorted({d.get("term_name", "") for d in deps if d.get("term_name")})[:10])
            answer = (
                f"{target.get('term_name', 'Term')} depends on: {dep_names}. "
                f"Depth={target.get('depth', 0)}; "
                f"cycle_detected={target.get('cycle_detected', False)}."
            )
        else:
            answer = (
                f"{target.get('term_name', 'Term')} has no tracked dependencies in the current resolution artifacts."
            )

        return {
            "question": question,
            "answer": answer,
            "citations": citations,
            "confidence": 0.9 if deps else 0.7,
        }

    @staticmethod
    def _flatten_dependencies(tree: dict[str, Any]) -> list[dict[str, Any]]:
        items: list[dict[str, Any]] = []
        for child in tree.get("depends_on", []):
            items.append(child)
            items.extend(QAAgent._flatten_dependencies(child))
        return items

    @staticmethod
    def _is_deal_ingested(deal_path: Path) -> bool:
        """Check if the deal has been ingested (vectorstore / extractions exist)."""
        vector_dirs = [deal_path / "vectorstore", deal_path / "vectors"]
        extraction_dirs = [
            deal_path / "documents" / "psa" / "extractions",
            deal_path / "extractions",
        ]

        has_vectors = any(d.exists() and any(d.iterdir()) for d in vector_dirs)
        has_extractions = any(d.exists() and any(d.glob("*.json")) for d in extraction_dirs)
        return has_vectors or has_extractions

    def _answer_question(
        self,
        deal_path: Path,
        question: str,
        n_results: int,
    ) -> dict[str, Any]:
        """Answer a single question using vector search + extraction fallback.

        Enhanced with (when llm_callable is provided and config flags are set):
        - **Multi-query expansion** (abs_multi_query_enabled): generate N query
          variants to maximise recall.
        - **HyDE** (abs_hyde_enabled): use a hypothetical answer document as an
          additional search query for better embedding alignment.
        - **CRAG** (abs_crag_enabled): grade retrieved chunks; re-retrieve with a
          reformulated query if the initial score is below the threshold.
        """
        # ── 1. Optionally build additional query variants via multi-query / HyDE ──
        search_queries: list[str] = [question]

        if self._llm is not None and getattr(self.config, "abs_multi_query_enabled", False):
            variants = self._generate_query_variants(question)
            search_queries.extend(variants)

        if self._llm is not None and getattr(self.config, "abs_hyde_enabled", False):
            hyde_doc = self._generate_hyde_doc(question)
            if hyde_doc:
                search_queries.append(hyde_doc)

        # ── 2. Retrieve chunks for all queries ────────────────────────────────────
        all_chunks: list[dict[str, Any]] = []
        for query in search_queries:
            all_chunks.extend(self._search_vectors(deal_path, query, n_results))
            all_chunks.extend(self._search_by_section(deal_path, query))

        if not all_chunks:
            all_chunks = self._search_extractions(deal_path, question)

        if not all_chunks:
            return {
                "question": question,
                "answer": "No relevant information found for this question.",
                "citations": [],
                "confidence": 0.0,
            }

        # ── 3. CRAG: grade and optionally re-retrieve ─────────────────────────────
        if self._llm is not None and getattr(self.config, "abs_crag_enabled", False):
            crag_threshold = float(getattr(self.config, "abs_crag_threshold", 0.85))
            avg_pre = sum(c.get("score", 0) for c in all_chunks) / max(len(all_chunks), 1)

            if avg_pre < crag_threshold:
                # Grade each chunk; keep only "relevant" chunks
                graded = self._crag_grade_chunks(question, all_chunks)
                relevant = [c for c, grade in graded if grade == "relevant"]

                if relevant:
                    all_chunks = relevant
                else:
                    # All chunks graded irrelevant — try a reformulated query
                    reformulated = self._crag_reformulate(question, all_chunks)
                    if reformulated:
                        extra = self._search_vectors(deal_path, reformulated, n_results)
                        if extra:
                            all_chunks = extra

        # ── 4. Deduplicate and rank ───────────────────────────────────────────────
        seen: set[str] = set()
        unique_chunks: list[dict[str, Any]] = []
        for chunk in all_chunks:
            text = chunk.get("text", "")[:200]
            if text not in seen:
                seen.add(text)
                unique_chunks.append(chunk)

        unique_chunks.sort(key=lambda c: c.get("score", 0), reverse=True)

        # ── 5. Build answer ───────────────────────────────────────────────────────
        answer_parts: list[str] = []
        citations: list[dict[str, Any]] = []
        for chunk in unique_chunks[:n_results]:
            text = chunk.get("text", "").strip()
            if text:
                answer_parts.append(text)
            citation = {
                "section": chunk.get("section", chunk.get("metadata", {}).get("section", "unknown")),
                "page": chunk.get("page", chunk.get("metadata", {}).get("page", "")),
                "score": round(chunk.get("score", 0.0), 4),
            }
            citations.append(citation)

        answer = "\n\n".join(answer_parts)
        avg_score = sum(c["score"] for c in citations) / max(len(citations), 1)

        return {
            "question": question,
            "answer": answer,
            "citations": citations,
            "confidence": round(avg_score, 4),
        }

    # ------------------------------------------------------------------
    # LLM-enhanced retrieval helpers
    # ------------------------------------------------------------------

    def _generate_query_variants(self, question: str) -> list[str]:
        """Generate alternative query phrasings via the LLM callable.

        Falls back to [] on any error.
        """
        count = int(getattr(self.config, "abs_multi_query_count", 6))
        prompt = (
            f"Generate {count} alternative phrasings of the following question about an ABS deal. "
            f"Return ONLY a JSON array of strings. No explanation.\n\n"
            f"Question: {question}"
        )
        try:
            raw = self._llm(prompt, None)
            # Parse first JSON array found in the response
            import re as _re
            m = _re.search(r"\[.*\]", raw, _re.DOTALL)
            if m:
                import json as _json
                variants = _json.loads(m.group(0))
                return [str(v).strip() for v in variants if v and str(v).strip()]
        except Exception as exc:
            logger.debug("Multi-query generation failed: %s", exc)
        return []

    def _generate_hyde_doc(self, question: str) -> str:
        """Generate a hypothetical answer document via the LLM callable.

        Falls back to "" on any error.
        """
        prompt = (
            "Write a one-paragraph hypothetical answer to the following question about an ABS deal. "
            "Use specific financial terminology. Reply with ONLY the paragraph text.\n\n"
            f"Question: {question}"
        )
        try:
            return self._llm(prompt, None).strip()
        except Exception as exc:
            logger.debug("HyDE generation failed: %s", exc)
        return ""

    def _crag_grade_chunks(
        self,
        question: str,
        chunks: list[dict[str, Any]],
    ) -> list[tuple[dict[str, Any], str]]:
        """Grade each chunk as 'relevant', 'irrelevant', or 'ambiguous'.

        Falls back to ['ambiguous', ...] on any error so no chunks are dropped.
        """
        results: list[tuple[dict[str, Any], str]] = []
        for chunk in chunks:
            text = chunk.get("text", "")[:400]
            prompt = (
                "Assess whether this text passage is relevant to the question.\n"
                "Reply with exactly one word: relevant, irrelevant, or ambiguous.\n\n"
                f"Question: {question}\n\nPassage: {text}"
            )
            try:
                grade = self._llm(prompt, None).strip().lower().split()[0]
                if grade not in ("relevant", "irrelevant", "ambiguous"):
                    grade = "ambiguous"
            except Exception as exc:
                logger.debug("CRAG grading failed: %s", exc)
                grade = "ambiguous"
            results.append((chunk, grade))
        return results

    def _crag_reformulate(self, question: str, chunks: list[dict[str, Any]]) -> str:
        """Ask the LLM to reformulate the question when initial retrieval was poor.

        Falls back to "" on any error.
        """
        context_sample = "\n".join(
            c.get("text", "")[:150] for c in chunks[:3]
        )
        prompt = (
            "The following retrieved passages did not directly answer the question. "
            "Reformulate the question to improve retrieval from a legal ABS document. "
            "Reply with ONLY the reformulated question.\n\n"
            f"Original question: {question}\n\nRetrieved sample:\n{context_sample}"
        )
        try:
            return self._llm(prompt, None).strip()
        except Exception as exc:
            logger.debug("CRAG reformulation failed: %s", exc)
        return ""

    def _search_vectors(
        self,
        deal_path: Path,
        query: str,
        n_results: int,
    ) -> list[dict[str, Any]]:
        """Search the deal's vector store."""
        try:
            from backend.abs.skills.vector_search import vector_search
            chroma_path = self.deal_scope.get_vectorstore_dir()
            collection_name = self.deal_scope.get_vector_collection()
            results = vector_search(
                query_text=query,
                collection_name=collection_name,
                chroma_path=chroma_path,
                n_results=n_results,
            )
            return [
                {
                    "text": r.text,
                    "score": r.score,
                    "metadata": r.metadata,
                    "section": r.metadata.get("section", ""),
                    "page": r.metadata.get("page", ""),
                }
                for r in results
            ]
        except Exception as exc:
            logger.info("Vector search unavailable (%s), falling back to extraction search", exc)
            return []

    def _search_by_section(
        self,
        deal_path: Path,
        query: str,
    ) -> list[dict[str, Any]]:
        """Search by section if query mentions a specific section."""
        # Detect if the query mentions a canonical section
        query_lower = query.lower()
        target_section = None
        for section in CANONICAL_SECTIONS:
            if section.replace("_", " ") in query_lower or section in query_lower:
                target_section = section
                break

        if not target_section:
            return []

        try:
            from backend.abs.skills.vector_search import vector_search
            chroma_path = self.deal_scope.get_vectorstore_dir()
            collection_name = self.deal_scope.get_vector_collection()
            results = vector_search(
                query_text=query,
                collection_name=collection_name,
                chroma_path=chroma_path,
                n_results=3,
                where_filter={"section": target_section},
            )
            return [
                {
                    "text": r.text,
                    "score": r.score,
                    "metadata": r.metadata,
                    "section": target_section,
                    "page": r.metadata.get("page", ""),
                }
                for r in results
            ]
        except Exception as exc:
            logger.debug("Section search failed: %s", exc)
            return []

    @staticmethod
    def _search_extractions(
        deal_path: Path,
        query: str,
    ) -> list[dict[str, Any]]:
        """Fallback: search extraction JSONs by keyword matching."""
        ext_dirs = [
            deal_path / "documents" / "psa" / "extractions",
            deal_path / "extractions",
        ]
        ext_dir = next((d for d in ext_dirs if d.exists()), None)
        if ext_dir is None:
            return []

        query_terms = set(query.lower().split())
        chunks: list[dict[str, Any]] = []

        for json_file in sorted(ext_dir.glob("*.json")):
            try:
                data = json.loads(json_file.read_text(encoding="utf-8"))
                items = data if isinstance(data, list) else data.get("items", [data])
                section = json_file.stem

                for item in items:
                    item_text = json.dumps(item, default=str).lower()
                    matches = sum(1 for t in query_terms if t in item_text)
                    if matches > 0:
                        score = matches / max(len(query_terms), 1)
                        text_parts = []
                        for key in ("term", "name", "description", "text", "value"):
                            val = item.get(key)
                            if val:
                                text_parts.append(f"{key}: {val}")
                        chunks.append({
                            "text": "; ".join(text_parts) if text_parts else str(item),
                            "score": score,
                            "section": section,
                            "page": item.get("page", ""),
                            "metadata": {"section": section, "source": "extraction"},
                        })
            except (json.JSONDecodeError, OSError):
                continue

        return sorted(chunks, key=lambda c: c["score"], reverse=True)

    # ------------------------------------------------------------------
    # Quality scoring overrides
    # ------------------------------------------------------------------

    def _score_completeness(self, result: Any, task: dict) -> float:
        answers = result.get("answers", [])
        questions = self._extract_questions(task)
        return 10.0 * len(answers) / max(len(questions), 1)

    def _score_accuracy(self, result: Any, task: dict) -> float:
        answers = result.get("answers", [])
        with_citations = sum(1 for a in answers if a.get("citations"))
        return 10.0 * with_citations / max(len(answers), 1) if answers else 5.0

    def _score_confidence(self, result: Any, task: dict) -> ConfidenceScore:
        answers = result.get("answers", [])
        if not answers:
            return ConfidenceScore(value=0.0, tier=ConfidenceTier.LOW, reasoning="No answers")
        avg_conf = sum(a.get("confidence", 0) for a in answers) / len(answers)
        tier = self._categorize_confidence(avg_conf)
        return ConfidenceScore(
            value=avg_conf, tier=tier,
            reasoning=f"Average retrieval score across {len(answers)} answers",
        )

    def _get_artifacts(self, result: Any) -> list[str]:
        return []
